### ISSUE TITLE
Cyclic Connection

### ISSUE THREAD

**Issue by Daguerreo** [klauer/qtpynodeeditor#35]
The open issue https://github.com/paceholder/nodeeditor/issues/198 actually has a working solution in the comments. I integrated it long time ago and had a problem with that, I don't know why he isn't merging it though.

This porting has the same issue or do implement that fix?

**Comment by klauer** [comment]
The issue is in this port as well.  My personal project that relies on qtpynodeeditor used networkx to get a digraph and break the cycles, but it's not as good as disallowing the connection creation to start with (plus, I'd rather not add the dependency here).

I think we could implement your suggested fix from the upstream issue, @Daguerreo.
